export const CHANGE_PLAYLIST = 'change_playlist'
export const CHANGE_SONG_INDEX = 'change_song_index'
export const CHANGE_FIRST_LOAD = 'change_first_load'
export const CHANGE_PLAY_SEQUENCE = 'change_play_sequence'
export const CHANGE_FORCE_PLAY = 'change_force_play'
export const CHANGE_LYRIC_LIST = 'change_lyric_list'
export const CHANGE_LYRIC_INDEX = 'change_lyric_index'